//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSplit.Crash.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSplit.Crash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Crash {
            get {
                object obj = ResourceManager.GetObject("Crash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crash1 {
            get {
                object obj = ResourceManager.GetObject("Crash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Stages&gt;
        ///  &lt;!-- N. Sanity Beach --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;&quot; Gold=&quot;&quot; Platinum=&quot;&quot; /&gt;
        ///  &lt;!-- Jungle Rollers --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;&quot; Gold=&quot;&quot; Platinum=&quot;&quot; /&gt;
        ///  &lt;!-- The Great Gate --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;&quot; Gold=&quot;&quot; Platinum=&quot;&quot; /&gt;
        ///  &lt;!-- Boulders --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;&quot; Gold=&quot;&quot; Platinum=&quot;&quot; /&gt;
        ///  &lt;!-- Upstream --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crash11 {
            get {
                return ResourceManager.GetString("Crash11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crash2 {
            get {
                object obj = ResourceManager.GetObject("Crash2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Stages&gt;
        ///  &lt;!-- Turtle Woods --&gt;
        ///  &lt;Stage Crystals=&quot;1&quot; Gems=&quot;1&quot; ColoredGem=&quot;Blue&quot; Boxes=&quot;62&quot; Sapphire=&quot;1:15.00&quot; Gold=&quot;0:56.87&quot; Platinum=&quot;0:45.47&quot; /&gt;
        ///  &lt;!-- Snow Go --&gt;
        ///  &lt;Stage Crystals=&quot;1&quot; Gems=&quot;1&quot; ColoredGem=&quot;Red&quot; Boxes=&quot;74&quot; Sapphire=&quot;1:10.00&quot; Gold=&quot;0:49.64&quot; Platinum=&quot;0:42.88&quot; /&gt;
        ///  &lt;!-- Hang Eight --&gt;
        ///  &lt;Stage Crystals=&quot;1&quot; Gems=&quot;2&quot; Boxes=&quot;74&quot; Sapphire=&quot;1:20.00&quot; Gold=&quot;1:02.93&quot; Platinum=&quot;0:56.24&quot; /&gt;
        ///  &lt;!-- The Pits --&gt;
        ///  &lt;Stage Crystals=&quot;1&quot; Gems=&quot;1&quot; Boxes=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crash21 {
            get {
                return ResourceManager.GetString("Crash21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crash3 {
            get {
                object obj = ResourceManager.GetObject("Crash3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Stages&gt;
        ///  &lt;!-- Toad Village --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;1:03.00&quot; Gold=&quot;0:57.50&quot; Platinum=&quot;0:44.03&quot; /&gt;
        ///  &lt;!-- Under Pressure --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;1:39.00&quot; Gold=&quot;1:10.90&quot; Platinum=&quot;1:03.50&quot; /&gt;
        ///  &lt;!-- Orient Express --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;0:41.00&quot; Gold=&quot;0:27.80&quot; Platinum=&quot;0:18.10&quot; /&gt;
        ///  &lt;!-- Bone Yard --&gt;
        ///  &lt;Stage Crystals=&quot;&quot; Gems=&quot;&quot; Boxes=&quot;&quot; Sapphire=&quot;1:45.00&quot; Gold=&quot;1:40.20&quot; P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crash31 {
            get {
                return ResourceManager.GetString("Crash31", resourceCulture);
            }
        }
    }
}
